// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingSystem.Data;

#nullable disable

namespace ParkingSystem.Data.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20260928130051_UsernameToEmail")]
    partial class UsernameToEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingSystem.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            SlotNumber = "S1"
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            SlotNumber = "S2"
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            SlotNumber = "S3"
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            SlotNumber = "S4"
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            SlotNumber = "S5"
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            SlotNumber = "S6"
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            SlotNumber = "S7"
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            SlotNumber = "S8"
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            SlotNumber = "S9"
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            SlotNumber = "S10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
